services:
  node:
    ports:
      - "9944:9944"
      - "9615:9615"
    image: aimosphere/airo
    container_name: node
    networks:
      demo_net:
        ipv4_address: 172.30.1.1
    command:
      - "--dev"
      - "--unsafe-rpc-external"
      - "--no-telemetry"
      - "--rpc-cors"
      - "all"

  cog-hello-world:
    image: cog-hello-world
    container_name: cog-hello-world
    networks:
      demo_net:
        ipv4_address: 172.30.2.1

  cog-resnet:
    image: cog-resnet
    container_name: cog-resnet
    networks:
      demo_net:
        ipv4_address: 172.30.2.2

  cog-health-client:
    image: cog-health-client
    container_name: cog-health-client
    ports:
      - "5001:5000"
    networks:
      demo_net:
        ipv4_address: 172.30.2.3

  cog-health-server:
    image: cog-health-server
    container_name: cog-health-server
    networks:
      demo_net:
        ipv4_address: 172.30.2.4

  wingman-bob:
    image: aimosphere/wingman
    container_name: wingman-bob
    ports:
      - "8000:8000"
    networks:
      demo_net:
        ipv4_address: 172.30.3.1
    environment:
      - AW_PORT=8000
      - AIRO_NODE=ws://node:9944
      - AIRO_SURI=//Bob
    depends_on:
      node:
        condition: service_started
      cog-hello-world:
        condition: service_started
      cog-resnet:
        condition: service_started
      cog-health-client:
        condition: service_started
      cog-health-server:
        condition: service_started
    restart: unless-stopped
    
  wingman-charlie:
    image: aimosphere/wingman
    container_name: wingman-charlie
    ports:
      - "8001:8000"
    networks:
      demo_net:
        ipv4_address: 172.30.3.2
    environment:
      - AW_PORT=8000
      - AIRO_NODE=ws://node:9944
      - AIRO_SURI=//Bob
    depends_on:
      node:
        condition: service_started
      cog-hello-world:
        condition: service_started
      cog-resnet:
        condition: service_started
      cog-health-client:
        condition: service_started
      cog-health-server:
        condition: service_started
    restart: unless-stopped

networks:
  demo_net:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
